### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by iamshnoo** [kddubey/cappr#3]
Hello,

I would like to use cappr in a research paper I am working on. Could you add a citation for the project that I can use in the paper?

P.S The related work section of the docs is very helpful as proof of this approach being common in research, thank you!

**Comment by kddubey** [comment]
I added a `CITATION.cff` file to the repo.

Click the "Cite this repository" dropdown button in the **About** section on the right side of the [repo homepage](https://github.com/kddubey/cappr).

Hope this helps!
